name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]

# GitHub Pages 액션이 필요로 하는 권한
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ⚠️ 핵심: npm lock/node_modules 제거 후 fresh install
      - name: Clean npm cache
        run: npm cache clean --force

      - name: Fresh install (no lock)
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install

      - name: Build
        run: npm run build

      # dist 를 Pages artifact로 업로드
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
